{% set name = "PyPhotometry" %}
{% set version = "0.0.5" %}
{% set url = "https://pypi.io/packages/source/" + name[0] + "/" + name + "/" + name + "-" + version + ".tar.gz" %}
# In case you wanna test locally
#{% set url = name ~ '-' ~ version ~ '.tar.gz' %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "{{ name }}-{{ version }}.tar.gz"
  url: "{{ url }}"
  sha256: 6782b7eb9c42393503eb6d85ffe463d628892a4c4fff49021bcc8855ae7cb179

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - matplotlib
    - numpy>=1.21.5
    - sqlalchemy
    - astropy
    - pip
    - python
  run:
    - matplotlib
    - numpy>=1.21.5
    - astropy
    - sqlalchemy
    - python

test:
  imports:
    - PyPhotometry

about:
  home: "https://github.com/neutrinomuon/PyPhotometry"
  license_file: 'LICENSE.txt'
  license_url: "https://github.com/neutrinomuon/PyPhotometry/LICENSE.txt"
  summary: "PyPhotometry is a Python package based on a Fortran legacy package that allows you to compute photometric fluxes and magnitudes in various photometric s
ystems. The package provides different magnitude systems"
  doc_url: "https://github.com/neutrinomuon/PyPhotometry"
  dev_url: "https://github.com/neutrinomuon/PyPhotometry"

extra:
  recipe-maintainers:
    - neutrinomuon